#! /usr/bin/python
# /* encoding: utf-8 */
# Copyright Altaire bot © Assassin, 2011 - 2012
# This program published under Apache 2.0 license
# See LICENSE.txt for more details
# My EMail: assassin@sonikelf.ru
# My XMPP-conference: bottiks@conference.jabber.ru
# My Site: bottiks.ucoz.ru
# AltaireConfigMaker

import sys, os
reload(sys).setdefaultencoding('utf8')

core = os.path.abspath(__file__)
coreDir = os.path.split(core)[0]
if coreDir: os.chdir(coreDir)


inp = lambda: unicode(raw_input().decode(sys.stdin.encoding))
perm = lambda text: 'u"%s"' % text
code_list = lambda list: '[u"%s"]' % '", u"'.join(list)

locales = list()
for file in os.listdir('locales'):
	if not (file.endswith('comms') or \
	file.endswith('help') or file == '.svn'):
		locales.append(file)

def printer(text):
	text = chr(10) + text
	try:
		sys.stdout.write(text)
		sys.stdout.flush()
	except: print text



jids = list()
printer("Enter bot's Jabber ID: ")
jids.append(inp())
printer('Whether all the Jabber IDs? (y/n): ')

while inp() in ('n', 'no'):
	printer("Enter bot's Jabber ID: ")
	jids.append(inp())
	printer('Whether all the Jabber IDs? (y/n)')



printer("Enter the password for bot's Jabber IDs (one for all): ")
passw = inp()



printer("Enter port for connecting all bot's Jabber IDs (default: 5222): ")
port = int(inp())



adms = list()
printer("Enter Jabber ID of admin of bot: ")
adms.append(inp())
printer("Whether all the admin's Jabber IDs? (y/n): ")

while inp() in ('no', 'n'):
	printer("Enter Jabber ID of admin of bot: ")
	adms.append(inp())
	printer("Whether all the admin's Jabber IDs? (y/n): ")



printer("Enter default bot's status: ")
stat = inp()



printer("Enter default bot's language (%s): " % ', '.join(locales))
lang = inp().upper()



settingsFile = 'other/settings.py'
folder = os.path.dirname(settingsFile)
if folder and (not os.path.exists(folder)): os.makedirs(folder)

temp = open(settingsFile, 'w')

forWrite = \
u'''#! /usr/bin/python2
# encoding: utf-8
# Copyright Altaire bot (C) Assassin, 2011 - 2012
# This program published under Apache 2.0 license
# See LICENSE for more details
# My EMail: assassin@sonikelf.ru
# settings-file for Altaire bot
# Generated by AltaireConfigMaker


jids = %s
password = %s
status = %s
port = %d
admins = %s
language = %s
debug = False''' % (code_list(jids), perm(passw), perm(stat), port, code_list(adms), perm(lang))

temp.write(forWrite.encode('utf8'))
temp.close()